#FROM node:10-alpine
#
#ARG NODE_ENV=production
#ENV NODE_ENV=${NODE_ENV}
#
## Install latest npm
#RUN npm i npm@latest -g
#
#WORKDIR /var/www
#
## Instal dependencies
#COPY package*.json ./
#RUN npm install
#
## Copy app code
#COPY ./src ./src
#
## https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
#USER node
#
#CMD ["node"]
